- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: 'yes'
    update_cache: yes
    cache_valid_time: 86400 #One day
    autoremove: yes

- name: Install apt packages
  become: true
  apt:
    name: 
      - git
      - xclip
      - silversearcher-ag
      - fonts-firacode
      - tmux
    state: present
    update_cache: yes

