- name: Add Docker GPG key
  apt_key: 
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present  
  become: true

- name: Add Docker Repository
  become: true
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: Install Docker packages
  apt:
    name: ['docker-ce','docker-ce-cli','containerd.io']
    state: present
  become: true

